### ISSUE TITLE
Can't compile 

### ISSUE THREAD

**Issue by emdio** [fogleman/MisterQueen#2]
Under Ubuntu, gcc 7.3.0

I cloned the repo, ran "make" and got the next error:

$ make
Creating directories
Beginning release build
Compiling: src/bb.c -> build/release/bb.o
Compiling: src/bk.c -> build/release/bk.o
Compiling: src/board.c -> build/release/board.o
src/board.c: In function ‘board_print’:
src/board.c:236:13: warning: ‘c’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             putchar(c);
             ^~~~~~~~~~
Compiling: src/book.c -> build/release/book.o
Compiling: src/deps/tinycthread/tinycthread.c -> build/release/deps/tinycthread/tinycthread.o
Compiling: src/eval.c -> build/release/eval.o
Compiling: src/gen.c -> build/release/gen.o
Compiling: src/main.c -> build/release/main.o
Compiling: src/move.c -> build/release/move.o
src/move.c: In function ‘score_move’:
src/move.c:162:9: warning: variable ‘piece_material’ set but not used [-Wunused-but-set-variable]
     int piece_material = 0;
         ^~~~~~~~~~~~~~
Compiling: src/opening.c -> build/release/opening.o
Compiling: src/perft.c -> build/release/perft.o
Compiling: src/search.c -> build/release/search.o
Compiling: src/table.c -> build/release/table.o
Compiling: src/uci.c -> build/release/uci.o
Compiling: src/util.c -> build/release/util.o
Linking: bin/release/main
build/release/deps/tinycthread/tinycthread.o: In function `mtx_init':
tinycthread.c:(.text+0x67): undefined reference to `pthread_mutexattr_init'
tinycthread.c:(.text+0x7a): undefined reference to `pthread_mutexattr_settype'
tinycthread.c:(.text+0x8f): undefined reference to `pthread_mutexattr_destroy'
build/release/deps/tinycthread/tinycthread.o: In function `mtx_trylock':
tinycthread.c:(.text+0x105): undefined reference to `pthread_mutex_trylock'
build/release/deps/tinycthread/tinycthread.o: In function `thrd_create':
tinycthread.c:(.text+0x241): undefined reference to `pthread_create'
build/release/deps/tinycthread/tinycthread.o: In function `thrd_join':
tinycthread.c:(.text+0x2fd): undefined reference to `pthread_join'
build/release/deps/tinycthread/tinycthread.o: In function `tss_create':
tinycthread.c:(.text+0x455): undefined reference to `pthread_key_create'
build/release/deps/tinycthread/tinycthread.o: In function `tss_set':
tinycthread.c:(.text+0x495): undefined reference to `pthread_setspecific'
build/release/deps/tinycthread/tinycthread.o: In function `tss_delete':
tinycthread.c:(.text+0x471): undefined reference to `pthread_key_delete'
build/release/deps/tinycthread/tinycthread.o: In function `tss_get':
tinycthread.c:(.text+0x481): undefined reference to `pthread_getspecific'
collect2: error: ld returned 1 exit status
Makefile:166: recipe for target 'bin/release/main' failed
make[1]: *** [bin/release/main] Error 1
Makefile:116: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by fogleman** [comment]
Without digging into it, I'm guessing you just need `-lpthread` in the linker flags.

**Comment by emdio** [comment]
Nice, that did the trick. Thanks a lot!
